name: bees_env
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pydot
  - python >=3.12
  - pyyaml
  - scikit-learn
  - scipy
  - anaconda::ipython
  - pydantic
  - redkit

